name: Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - core/**
  pull_request:
    branches: [ "main" ]
    paths:
      - core/**

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        cache: yarn
        node-version: 16

    - name: Install
      working-directory: ./core
      run: |
        npm ci

    - name: Build
      working-directory: ./core
      run: |
        npm run build
