name: Build Editor

on:
  push:
    branches: [ "main" ]
    paths:
      - Editor/**
  pull_request:
    branches: [ "main" ]
    paths:
      - Editor/**

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup
      working-directory: ./Editor
      run: |
        npm ci

    - name: Lint
      working-directory: ./Editor
      run: |
        npm run lint
