name: Lint

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - core/**
  pull_request:
    branches: [ "main" ]
    paths:
      - core/**

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        cache: yarn
        cache-dependency-path: core/yarn.lock
        node-version: 16

    - name: Install
      working-directory: ./core
      run: |
        yarn install --frozen-lockfile

    - name: Lint
      working-directory: ./core
      run: |
        yarn lint
