name: Website Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: --cwd website install # will run `yarn install` command
      - name: Build
        uses: borales/actions-yarn@v3.0.0
        working-directory: website
        with:
          cmd: --cwd website build # will run `yarn build` command
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./website/dist